### PR TITLE
Adding .tgz extension to github file search

### PR DESCRIPTION
**Pull request by drmikecrowe**

### CODE REVIEW

**Comment by jpillora** [comment]
Can you remove the change to use .local/bin ?

I don't think everyone will have that directory?

```
m1 ~/.local ls -lah
Permissions Size User     Date Modified Name
drwx------     - jpillora  8 Dec  2020  share
```

**Comment by jpillora** [comment]
Instead of updating the go template, we could update the script to:

1. check .local/bin exists
2. check .local/bin is in the PATH
3. not sudo move
4. not root user

then use .local/bin

**Comment by drmikecrowe** [comment]
Yeah, that's what I was trying to accomplish but I was new to Go

**Comment by drmikecrowe** [comment]
Reverted.  

Here's what I was trying to implement:
* If  `.SudoMove` && `.MoveToPath` -- use `/usr/local/bin`
* If `.MoveToPath` use `$HOME/.local/bin` (which seems to be the standard)

**Comment by jpillora** [comment]
Thanks! Will checkout the PR soon

**Pull request merged**
